modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="amulets"
version="1.0.0"
displayName="Amulets"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="matty, MCreator"

[[dependencies.amulets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




